export { default as Home } from './home';
export { default as Navbar } from './navbar';
export { default as Login } from './login';
export { default as Signup } from './signup';
export { default as MainPage } from './mainpage';
export { default as MainNavBar } from './mainnavbar';
export { default as AnimeCard } from './animecard';
export { default as SinglePage } from './singlepage';
export { default as MyAnimeList } from './myanimelist';